export const continentalMesoSector = 19;

export const mesoSectors: [number, string][] = [
  [19, 'Continental U.S.'],
  [11, 'Northwest'],
  [12, 'Southwest'],
  [13, 'Northern Plains'],
  [14, 'Central Plains'],
  [15, 'Southern Plains'],
  [16, 'Northeast'],
  [18, 'Southeast'],
  [17, 'Atlantic'],
  [20, 'Midwest'],
  [21, 'Great Lakes'],
  [22, 'Mountain West'],
];

export const wcpSectors: [number, string][] = [
  [19, 'us'],
  [11, 'nw'],
  [12, 'sw'],
  [13, 'nc'],
  [14, 'cc'],
  [15, 'sc'],
  [16, 'ne'],
  [18, 'se'],
  [17, 'ce'],
  // TODO: "North America" / `na`
];

// export const mesoParams: [string, string][] = [
//   ['300mb', '300 mb Analysis'],
//   ['500mb', '500 mb Analysis'],
//   ['700mb', '700 mb Analysis'],
//   ['850mb', '850 mb Analysis'],
//   ['ageo', '300 mb Jet Circulation'],
//   ['500mb_chg', '500 mb Height Change'],
//   ['pmsl', 'Sfc Pressure / Wind'],
//   ['ttd', 'Temp / Dewpoint / Wind'],
//   ['3cvr', 'Sfc Vorticity / 3CAPE'],
//   ['stor', 'Sig Tornado (fixed layer)'],
//   ['stpc', 'Sig Tornado (effective layer)'],
//   ['stpc5', 'Sig Tornado (0-500m SRH)'],
//   ['dvvr', 'Sfc Convergence & Vorticity'],
//   ['scp', 'Supercell Composite'],
//   ['lr3c', '0-3km Lapse Rate & ML3CAPE'],
//   ['lclh', 'LCL (Cloud Base) Height'],
//   ['nstp', 'Non-supercell Tornado'],
//   ['desp', 'Enhanced Stretching Potential'],
//   ['effh', 'Eff. inflow base + ESRH'],
//   ['srh5', 'Eff. inflow base + 0-500m SRH'],
//   ['mlcp', 'MLCAPE / MLCIN'],
//   ['hail', 'Hail Parameters'],
//   ['mbcp', 'Microburst Composite'],
//   ['ddiv', 'Differential Divergence'],
//   ['vadv', 'Vorticity Advection'],
//   ['ddrh', 'Dendritic Growth Layer'],
//   ['snsq', 'Snow Squall'],
//   ['oprh', 'OPRH'],
//   ['skewt', 'Skew-Ts'],
//   ['skewt-winter', 'Skew-Ts (winter)'],
//   ['hodo', 'Hodographs'],
// ];

export const spcMesoanalysisParams: [string, [string, string][]][] = [
  [
    'Observations',
    [
      ['bigsfc', 'Surface Observations'],
      ['pdfsfc', 'Printable Surface Map [PDF]'],
      ['1kmv', 'Visible Satellite'],
      ['rgnlrad', 'Radar Base Reflectivity'],
      ['vadprof', 'Vad/Profiler Data'],
    ],
  ],
  [
    'Surface',
    [
      ['pmsl', 'MSL Pressure/Wind'],
      ['ttd', 'Temp/Wind/Dwpt'],
      ['thet', 'MSL Pressure/Theta-E/Wind'],
      ['mcon', 'Moisture Convergence'],
      ['thea', 'Theta-E Advection'],
      ['mxth', 'Mixing Ratio / Theta'],
      ['icon', 'Instantaneous Contraction Rate (sfc)'],
      ['trap', 'Fluid Trapping (sfc)'],
      ['vtm', 'Velocity Tensor Magnitude (sfc)'],
      ['dvvr', 'Divergence and Vorticity (sfc)'],
      ['def', 'Deformation and Axes of Dilitation (sfc)'],
      ['pchg', '2-hour Pressure Change'],
      ['temp_chg', '3-hour Temp Change'],
      ['dwpt_chg', '3-hour Dwpt Change'],
      ['mixr_chg', '3-hour 100mb Mixing Ratio Change'],
      ['thte_chg', '3-hour Theta-E Change'],
    ],
  ],
  [
    'Upper Air',
    [
      ['925mb', '925mb Analysis'],
      ['850mb', '850mb Analysis'],
      ['850mb2', '850mb Analysis (version 2)'],
      ['700mb', '700mb Analysis'],
      ['500mb', '500mb Analysis'],
      ['300mb', '300mb Analysis'],
      ['dlcp', 'Deep Moist Convergence'],
      ['tadv_925', '925mb Temp Advection'],
      ['tadv', '850mb Temp Advection'],
      ['7tad', '700mb Temp Advection'],
      ['sfnt', 'Sfc Frontogenesis'],
      ['9fnt', '925mb Frontogenesis'],
      ['8fnt', '850mb Frontogenesis'],
      ['7fnt', '700mb Frontogenesis'],
      ['925f', '1000-925mb Frontogenesis'],
      ['98ft', '925-850mb Frontogenesis'],
      ['857f', '850-700mb Frontogenesis'],
      ['75ft', '700-500mb Frontogenesis'],
      ['vadv', '700-400mb Diff. Vorticity Advection'],
      ['padv', '400-250mb Pot. Vorticity Advection'],
      ['ddiv', '850-250mb Diff. Divergence'],
      ['ageo', '300mb Jet Circulation'],
      ['500mb_chg', '12-hour 500mb Height Change'],
      ['trap_500', 'Fluid Trapping (500mb)'],
      ['trap_250', 'Fluid Trapping (250mb)'],
    ],
  ],
  [
    'Thermodynamics',
    [
      ['sbcp', 'CAPE - Surface-Based'],
      ['mlcp', 'CAPE - 100mb Mixed-Layer'],
      ['mucp', 'CAPE - Most-Unstable / LPL Height'],
      ['eltm', 'EL Temp / MUCAPE / MUCIN'],
      ['ncap', 'CAPE - Normalized'],
      ['dcape', 'CAPE - Downdraft'],
      ['muli', 'Surface-based Lifted Index'],
      ['laps', 'Mid-Level Lapse Rates'],
      ['lllr', 'Low-Level Lapse Rates'],
      ['maxlr', 'Max 2-6 km AGL Lapse Rate'],
      ['lclh', 'LCL Height'],
      ['lfch', 'LFC Height'],
      ['lfrh', 'LCL-LFC Mean RH'],
      ['sbcp_chg', '3-hour Surface-Based CAPE Change'],
      ['sbcn_chg', '3-hour Surface-Based CIN Change'],
      ['mlcp_chg', '3-hour 100mb Mixed-Layer CAPE Change'],
      ['mucp_chg', '3-hour Most-Unstable CAPE Change'],
      ['lllr_chg', '3-hour Low-Level LR Change'],
      ['laps_chg', '6-hour Mid-Level LR Change'],
      ['skewt', '*New* Skew-T Maps'],
    ],
  ],
  [
    'Wind Shear',
    [
      ['eshr', 'Bulk Shear - Effective'],
      ['shr1', 'Bulk Shear - Sfc-1km'],
      ['shr3', 'Bulk Shear - Sfc-3km'],
      ['shr6', 'Bulk Shear - Sfc-6km'],
      ['shr8', 'Bulk Shear - Sfc-8km'],
      ['brns', 'BRN Shear'],
      ['effh', 'SR Helicity - Effective'],
      ['srh5', 'SR Helicity - Sfc-500m'],
      ['srh1', 'SR Helicity - Sfc-1km'],
      ['srh3', 'SR Helicity - Sfc-3km'],
      ['llsr', 'SR Wind - Sfc-2km'],
      ['mlsr', 'SR Wind - 4-6km'],
      ['ulsr', 'SR Wind - 9-11km'],
      ['alsr', 'SR Wind - Anvil Level'],
      ['mnwd', '850-300mb Mean Wind'],
      ['xover', '850 and 500mb Winds'],
      ['shr1_chg', '3hr Sfc-1km Bulk Shear Change'],
      ['srh3_chg', '3hr Sfc-3km SR Helicity Change'],
      ['shr6_chg', '3hr Sfc-6km Bulk Shear Change'],
      ['hodo', '*New* Hodograph Map'],
    ],
  ],
  [
    'Composite Indices',
    [
      ['scp', 'Supercell Composite'],
      ['lscp', 'Supercell Composite (left-moving)'],
      ['stor', 'Sgfnt Tornado (fixed layer)'],
      ['stpc', 'Sgfnt Tornado (effective layer)'],
      ['stpc5', '*New* Sgfnt Tornado (using 0-500m SRH )'],
      ['sigt1', 'Cond. Prob. Sigtor (Eqn 1)'],
      ['sigt2', 'Cond. Prob. Sigtor (Eqn 2)'],
      ['nstp', 'Non-Supercell Tornado'],
      ['vtp3', 'Violent Tornado Parameter (VTP)'],
      ['sigh', 'Sgfnt Hail'],
      ['sars1', 'SARS Hail Size'],
      ['sars2', 'SARS Sig. Hail Percentage'],
      ['lghl', 'Large Hail Parameter'],
      ['dcp', 'Derecho Composite'],
      ['cbsig', 'Craven/Brooks Sgfnt Severe'],
      ['brn', 'Bulk Richardson Number'],
      ['mcsm', 'MCS Maintenance'],
      ['mbcp', 'Microburst Composite'],
      ['desp', 'Enhanced Stretching Potential'],
      ['ehi1', 'EHI - Sfc-1km'],
      ['ehi3', 'EHI - Sfc-3km'],
      ['vgp3', 'VGP - Sfc-3km'],
      ['crit', 'Critical Angle'],
    ],
  ],
  [
    'Multi-Parameter Fields',
    [
      ['mlcp_eshr', '100mb Mixed-Layer CAPE / Effective Bulk Shear'],
      ['cpsh', 'Most-Unstable CAPE / Effective Bulk Shear'],
      ['comp', 'Most-Unstable LI / 850 & 500mb Winds'],
      ['lcls', 'LCL Height / Sfc-1km SR Helicity'],
      ['lr3c', 'Sfc-3km Lapse Rate / Sfc-3km MLCAPE'],
      ['3cape_shr3', '*New* Bulk Shear - Sfc-3km / Sfc-3km MLCAPE'],
      ['3cvr', 'Sfc Vorticity / Sfc-3km MLCAPE'],
      ['tdlr', 'Sfc Dwpt / 700-500mb Lapse Rates'],
      ['hail', 'Hail Parameters'],
      [
        'qlcs1',
        'Lowest 3km max. Theta-e diff., MUCAPE, and 0-3km vector shear',
      ],
      [
        'qlcs2',
        'Lowest 3km max. Theta-e diff., MLCAPE, and 0-3km vector shear',
      ],
    ],
  ],
  [
    'Heavy Rain',
    [
      ['pwtr', 'Precipitable Water'],
      ['pwtr2', 'Precipitable Water (w/ 850mb Moisture Transport Vector)'],
      ['tran', '850mb Moisture Transport'],
      ['tran_925', '925mb Moisture Transport'],
      ['tran_925-850', '925-850mb Moisture Transport'],
      ['prop', 'Upwind Propagation Vector'],
      ['peff', 'Precipitation Potential Placement'],
      ['mixr', '100mb Mean Mixing Ratio'],
    ],
  ],
  [
    'Winter Weather',
    [
      ['ptyp', 'Precipitation Type'],
      ['fztp', 'Near-Freezing Surface Temp'],
      ['swbt', 'Surface Wet-Bulb Temp'],
      ['fzlv', 'Freezing Level'],
      ['thck', 'Critical Thicknesses'],
      ['epvl', '800-750mb EPVg'],
      ['epvm', '650-500mb EPVg'],
      ['les1', 'Lake Effect Snow 1'],
      ['les2', 'Lake Effect Snow 2'],
      ['snsq', 'Snow Squall Parameter'],
      ['dend', 'Dendritic Growth Layer Depth'],
      ['dendrh', 'Dendritic Growth Layer RH'],
      ['ddrh', 'Dendritic Growth Layer Depth & RH'],
      ['mxwb', 'Max Wet Bulb Temperature'],
      ['skewt-winter', '*New* Winter Skew-T Maps'],
    ],
  ],
  [
    'Fire Weather',
    [
      ['sfir', 'Sfc RH / Temp / Wind'],
      ['fosb', 'Fosberg Index'],
      ['lfrh2', 'LCL-LFC Mean RH (fire wx version)'],
    ],
  ],
  [
    'Classic',
    [
      ['ttot', 'Total Totals'],
      ['kidx', 'K-Index'],
      ['show', 'Showalter Index'],
    ],
  ],
  [
    'Beta',
    [
      ['sherbe', 'SHERBE'],
      ['moshe', 'Modified SHERBE'],
      ['cwasp', 'CWASP'],
      ['tehi', '*New* Tornadic 0-1km EHI'],
      ['tts', '*New* Tornadic Tilting & Stretching'],
      ['oprh', 'OPRH'],
      ['ptstpe', 'Prob EF0+ (conditional on RM supercell)'],
      ['pstpe', 'Prob EF2+ (conditional on RM supercell)'],
      ['pvstpe', 'Prob EF4+ (conditional on RM supercell)'],
      ['pw3k', 'PW * 3kmRH'],
    ],
  ],
];

export const mesoParams: [string, string][] = spcMesoanalysisParams.flatMap(
  ([_category, params]) => params,
);

export const mesoSectorMap = new Map(mesoSectors);
export const wpcSectorMap = new Map(wcpSectors);
export const mesoParamMap = new Map(mesoParams);
